name: Comment

on: issue_comment

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
