name: Label n Stuff

on:
  pull_request:
    types: [opened, reopened, ready_for_review, converted_to_draft]
    branches: [master]

jobs:
  label-n-stuff:
    runs-on: ubuntu-latest
    steps:
      - run: echo "opened? ${{ github.event.action }}"

      - name: Is Draft
        id: is-pr-draft
        run: |
          echo "::set-output name=result::${{ toJson(github.event.pull_request.draft == true) }}"

      - name: WTF
        run: echo ${{ fromJson(steps.is-pr-draft.outputs.result) == false }}

      - name: Jira issue can be created
        id: jira-issue-can-be-created
        shell: bash
        run: |
          echo "::set-output name=result::${{ fromJson(steps.is-pr-draft.outputs.result) == false && !contains(github.event.pull_request.labels.*.name, 'jira issue created') }}"

      - name: Handle labels for Draft PR
        if: ${{ fromJson(steps.is-pr-draft.outputs.result) }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "wip, do not review"

      - name: Handle labels for non-Draft PR
        if: ${{ !fromJson(steps.is-pr-draft.outputs.result) }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "jira issue created"
          remove-labels: "wip, do not review"

      - name: Simulate action
        if: ${{ fromJson(steps.is-pr-draft.outputs.result) == false && fromJson(steps.jira-issue-can-be-created.outputs.result) == true }}
        run: |
          echo "yay!"

      - name: PR title
        shell: bash
        id: title
        run: |
          echo "::set-output name=result::'${{ fromJson(steps.is-pr-draft.outputs.result) }}'"

      - name: Notify JIRA
        shell: bash
        run: |
          curl -X POST -H 'Content-type: application/json' \
          "https://google.com" \
          --data '{"title":"${{ fromJson(steps.title.outputs.result) }}"}'
