name: Label n Stuff

on: 
  pull_request:
    branches:
      - master
    types: [opened, reopened, ready_for_review]

jobs:
  label-n-stuff:
    runs-on: ubuntu-latest
    steps:
      - run: echo "nice"

      - name: Has Label
        if: contains(github.event.pull_request.labels.*.name, 'tmp label')
        run: echo "HAS LABEL"

      - name: Labeling
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "tmp label, bug"
          remove-labels: "in progress"
