name: Label n Stuff

on: 
  pull_request:
    branches:
      - master
    types: [opened, reopened, ready_for_review]

jobs:
  label-n-stuff:
    runs-on: ubuntu-latest
    steps:
      - run: echo "nice"

      - run: echo "${{ github.event.label.name }}"

      - name: Has Label
        if: ${{ github.event.label.name == 'tmp label' }}
        run: echo "HAS LABEL"
