name: Label n Stuff

on:
  pull_request:
    types: [opened, reopened, ready_for_review, converted_to_draft]
    branches: [master]

jobs:
  label-n-stuff:
    runs-on: ubuntu-latest
    steps:
      - run: echo "nice"

      - name: Is Draft
        id: is-pr-eligible
        run: |
          echo "::set-output name=result::${{ toJson(github.event.pull_request.draft == true) }}"

      - name: WTF
        run: echo ${{ fromJson(steps.is-pr-eligible.outputs.result) == false }}

      - name: Handle labels for Draft PR
        if: ${{ fromJson(steps.is-pr-eligible.outputs.result) }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "wip"

      - name: Handle labels for non-Draft PR
        if: ${{ !fromJson(steps.is-pr-eligible.outputs.result) }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "jira issue created"
          remove-labels: "wip"

      - name: PR has label - JIRA issue created
        id: jira-issue-created
        if: contains(github.event.pull_request.labels.*.name, 'jira issue created')
        shell: bash
        run: |
          echo "::set-output name=result::true"

      - name: Simulate action
        if: ${{ fromJson(steps.is-pr-eligible.outputs.result) == true && fromJson(steps.jira-issue-created.outputs.result == true) }}
        run: |
          echo "yay!"
