name: Runs Once

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches:
      - master

jobs:
  runs-once:
    runs-on: ubuntu-latest
    name: Runs Once
    steps:
      - name: TMP
        run: |
          echo ${{ github.run_id }} &&
          echo ${{ github.run_number }} &&
          echo ${{ github.run_attempt }}
