name: Ready For Review

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - master
    types: [opened, reopened, ready_for_review]

jobs:
  ready-for-review:
    if: github.event.pull_request.draft == false && !(github.actor == 'dependabot[bot]')
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 Ready for review!"
      - run: echo "${{ github.ref }} ${{ github.repository }}"

    - name: Notify JIRA
      shell: bash
      env:
        TITLE: ${{ fromJson({data: "something"}) }} | tr -d "'"
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"data": {"author":"${{fromJson(steps.get-pr.outputs.data).user.login}}", "author_url":"${{fromJson(steps.get-pr.outputs.data).user.html_url}}", "title":"$TITLE", "number":"${{fromJson(steps.get-pr.outputs.data).number}}", "url":"${{fromJson(steps.get-pr.outputs.data).html_url}}", "repo":"$REPO"}}' \
        $JIRA_HOOK
