name: Ready For Review

on:
  push:
    branches-ignore: 
      - "dependabot-**"
    types: [opened, reopened, ready_for_review]

jobs:
  ready-for-review:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 Ready for review!"
      - run: echo "${{ github.ref }} ${{ github.repository }}"
