name: Ready For Review

on:
  pull_request:
    branches: 
      - master
    types: [opened, reopened, ready_for_review]

jobs:
  ready-for-review:
    if: github.event.pull_request.draft == false && !(github.actor == 'dependabot[bot]')
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 Ready for review!"
      - run: echo "${{ github.ref }} ${{ github.repository }}"
