name: Ready For Review

on:
  pull_request:
    branches-ignore: "dependabot-**"
    branches:
      - master
    types: [opened, reopened, ready_for_review]

jobs:
  ready-for-review:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 Ready for review!"
